[build-system]
requires = [
    "setuptools>=68",
    "setuptools_scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "mavparser"
dynamic = ["version"]
description = "Fast ArduPilot DataFlash BIN parser"
readme = "PYPI_README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Shmuel Barda" }]

[project.optional-dependencies]
test = [
    "pytest>=8",
    "pymavlink==2.4.42"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
include = ["mavparser*"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "no-local-version"
tag_regex = "^v(?P<version>.*)$"

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-* cp313-*"
skip = "*-win32 *-manylinux_i686 pp*"


test-skip = "cp39-*aarch64* cp310-*aarch64* cp312-*aarch64* cp313-*aarch64*"

test-extras = ["test"]
test-command = "pytest --import-mode=importlib {project}/tests"

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]